# generates #defines for C0..C7 (naturals + sharps/flats) and P_ (delta phase)
from math import pow
OVERSAMPLE=2
notes=[('C',0),('D',2),('E',4),('F',5),('G',7),('A',9),('B',11)]
midi=lambda n: int(n-48) # remove c3
m2p=lambda m: pow(2.0, (m-150.2326448623-(OVERSAMPLE-1)*12.0)/12.0)
m2f=lambda m: pow(2.0, (m-69)/12.0)*440.0
lines=[f"// generated by scripts/notes.py with OVERSAMPLE={OVERSAMPLE}"]
for o in range(0,8):
    base=12*(o+1)
    for name, i_white in notes:
        for i,suffix in enumerate(['b','', 's']):
            m=base+i_white+i-1
            v=m2p(m)
            f=m2f(m)
            nm = f"{name}{suffix}"
            lines.append(f"#define {nm}{o} {midi(m)}")
            lines.append(f"#define P_{nm}{o} {v:.9f}f")
            lines.append(f"#define F_{nm}{o} {f:.9f}f")
with open("src/notes.h", "w") as f:
    f.write("\n".join(lines))
