# generates #defines for C0..C7 (naturals + sharps/flats) and P_ (delta phase)
from math import pow
OVERSAMPLE=2
chrom=[('C',),('Cs','Db'),('D',),('Ds','Eb'),('E',),('F',),('Fs','Gb'),('G',),('Gs','Ab'),('A',),('As','Bb'),('B',)]
midi=lambda n: int(n)
m2p=lambda m: pow(2.0, (m-150.2326448623-(OVERSAMPLE-1)*12.0)/12.0)
lines=[f"// generated by scripts/notes.py with OVERSAMPLE={OVERSAMPLE}"]
for o in range(0,8):
    base=12*(o+1)
    for i,names in enumerate(chrom):
        m=base+i
        v=m2p(m)
        for nm in names:
            lines.append(f"#define {nm}{o} {midi(m)}")
            lines.append(f"#define P_{nm}{o} {v:.9f}f")
with open("notes.h", "w") as f:
    f.write("\n".join(lines))
