// enum, shortname, default
// the first 3 must be number, note, sound to match the value type enum
X(P_NUMBER, ":",0) // a number not yet assigned a meaning :)
X(P_NOTE, "note", C3)
X(P_SOUND,"s", 0) // an index into the sound map
X(P_GATE, "^", 0.75f)
X(P_CUTOFF, "cut", 24000.f)
X(P_RESONANCE, "res", 0)
X(P_ENV2VCF, "env2vcf", 0)
X(P_ENV2FOLD, "env2fold", 0)
X(P_ENV2DIST, "env2dist", 0)
X(P_DIST, "dist", 0)
X(P_FOLD, "fold", 0)
X(P_ATT, "att", 0.0f)
X(P_DEC, "dec", 0.3f)
X(P_SUS, "sus", 1.f)
X(P_REL, "rel", 0.0f)
X(P_ATT2, "att2", 0.0f)
X(P_DEC2, "dec2", 0.3f)
X(P_SUS2, "sus2", 1.f)
X(P_REL2, "rel2", 0.0f)
X(P_GAIN, "gain", 0.75f)
X(P_PAN, "pan", 0.5f)
X(P_LOOPS, "loops", 0.f)
X(P_LOOPE, "loope", 0.f)
X(P_FROM, "from", 0.f)
X(P_TO, "to", 1.f)
X(P_VIB, "vib", 0.f)
X(P_VIB_FREQ, "vibf", 0.f)
X(P_GLIDE, "glide", 0.f)
X(P_STRING, "string", 0.f)
X(P_SCALEBITS, "scale", 0.f)
#undef X
